# Basic Configuration
title: Your Awesome Book Title
author: Your Name
email: your-email@example.com
description: >- # this means to ignore newlines until "baseurl:"
  A short and engaging description of your book.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: your_twitter_handle
github_username:  your_github_handle

# Build settings
theme: null # We are not using a gem-based theme here, but copying files
# Instead of `theme: forty-jekyll-theme`, we'd copy the files.
# For GitHub Pages, you might use remote_theme: andrewbanchich/forty-jekyll-theme
# However, the theme's docs say to fork it, implying direct file usage.
# For now, we'll assume files will be copied into the repo.

plugins:
  - jekyll-feed

# Forty theme specific settings (placeholders, to be filled from the original theme's _config.yml)
# These would typically be more extensive.
tiles-source: pages # Can be 'pages' or 'posts'
tiles-count: 6

# Social Media Navbar links
social-network-links:
  email: "your-email@example.com"
  rss: true # Show RSS link
  twitter: your_twitter_handle
  facebook: your_facebook_handle
  google-plus: your_googleplus_handle # Or other networks
  instagram: your_instagram_handle
  linkedin: your_linkedin_handle
  github: your_github_handle
  # Add or remove social networks as needed

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal list regardless of how it is defined globally.
#
# Exclude[custom] is used to exclude files or directories that are temporary or sensitive,
# and should not be committed to your git repository.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
